"use client";

import { Bold, Heading2, Italic, Link2, List, ListOrdered } from "lucide-react";
import { useEffect, useRef } from "react";

export function RichTextEditor({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const editor = useRef<HTMLDivElement>(null);
  useEffect(() => { if (editor.current && editor.current.innerHTML !== value) editor.current.innerHTML = value; }, [value]);
  function command(name: string, argument?: string) { editor.current?.focus(); if (name === "createLink") { const url = window.prompt("Link URL"); if (!url) return; document.execCommand(name, false, url); } else document.execCommand(name, false, argument); onChange(editor.current?.innerHTML ?? ""); }
  return <div className="overflow-hidden rounded-2xl border border-line bg-white focus-within:border-coral focus-within:ring-4 focus-within:ring-coral/10"><div className="flex flex-wrap gap-1 border-b border-line bg-mist/40 p-2"><button type="button" aria-label="Bold" onClick={() => command("bold")} className="grid h-9 w-9 place-items-center rounded-lg text-slate hover:bg-white hover:text-ink"><Bold size={16} /></button><button type="button" aria-label="Italic" onClick={() => command("italic")} className="grid h-9 w-9 place-items-center rounded-lg text-slate hover:bg-white hover:text-ink"><Italic size={16} /></button><button type="button" aria-label="Heading" onClick={() => command("formatBlock", "h2")} className="grid h-9 w-9 place-items-center rounded-lg text-slate hover:bg-white hover:text-ink"><Heading2 size={16} /></button><button type="button" aria-label="Bulleted list" onClick={() => command("insertUnorderedList")} className="grid h-9 w-9 place-items-center rounded-lg text-slate hover:bg-white hover:text-ink"><List size={16} /></button><button type="button" aria-label="Numbered list" onClick={() => command("insertOrderedList")} className="grid h-9 w-9 place-items-center rounded-lg text-slate hover:bg-white hover:text-ink"><ListOrdered size={16} /></button><button type="button" aria-label="Add link" onClick={() => command("createLink")} className="grid h-9 w-9 place-items-center rounded-lg text-slate hover:bg-white hover:text-ink"><Link2 size={16} /></button></div><div ref={editor} contentEditable role="textbox" aria-label="Story body" aria-multiline="true" onInput={() => onChange(editor.current?.innerHTML ?? "")} className="min-h-72 p-5 text-[15px] leading-7 text-ink outline-none" data-placeholder="Write the story here..." /> </div>;
}
