"use client";

import { AdminRoute, PermissionRoute } from "@/components/auth/ProtectedRoute";
import { AdminShell } from "@/components/layout/AdminShell";
import { Alert } from "@/components/ui/Alert";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import { LoadingState } from "@/components/ui/LoadingState";
import { PageHeader } from "@/components/ui/PageHeader";
import { adminApi } from "@/lib/api/admin";
import { ApiClientError } from "@/lib/api/client";
import type { Tag } from "@/lib/types";
import { Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useAuth } from "@/components/auth/AuthProvider";

function TagsContent() { const { token } = useAuth(); const [items, setItems] = useState<Tag[]>([]); const [search, setSearch] = useState(""); const [editing, setEditing] = useState<Tag | null>(null); const [adding, setAdding] = useState(false); const [name, setName] = useState(""); const [slug, setSlug] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  function load() { if (!token) return; setLoading(true); adminApi.tags(token, search).then(setItems).catch((reason) => setError(reason instanceof ApiClientError ? reason.message : "Could not load tags.")).finally(() => setLoading(false)); }
  useEffect(load, [token, search]); function start(tag?: Tag) { setEditing(tag ?? null); setAdding(!tag); setName(tag?.name ?? ""); setSlug(tag?.slug ?? ""); setError(""); }
  async function save(event: React.FormEvent) { event.preventDefault(); if (!token) return; setSaving(true); try { const payload = { name, slug: slug || undefined }; if (editing) await adminApi.updateTag(token, editing.id, payload); else await adminApi.createTag(token, payload); setNotice(editing ? "Tag updated." : "Tag created."); start(); load(); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Could not save tag."); } finally { setSaving(false); } }
  async function remove(tag: Tag) { if (!token || !window.confirm(`Delete #${tag.name}?`)) return; try { await adminApi.deleteTag(token, tag.id); setNotice("Tag deleted."); load(); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Could not delete tag."); } }
  return <AdminShell><div className="flex flex-col justify-between gap-5 border-b border-line pb-8 sm:flex-row sm:items-end"><PageHeader eyebrow="Content" title="Tags" description="Maintain reusable tags for story discovery and filtering." /><Button onClick={() => start()}><Plus size={16} /> Add tag</Button></div><div className="mt-7 max-w-xl"><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate" size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search tags" aria-label="Search tags" className="min-h-12 w-full rounded-xl border border-line bg-white pl-11 pr-4 text-sm outline-none focus:border-coral focus:ring-4 focus:ring-coral/10" /></div></div>{notice ? <div className="mt-6"><Alert type="success">{notice}</Alert></div> : null}{error ? <div className="mt-6"><Alert>{error}</Alert></div> : null}{adding || editing ? <Card className="mt-7 p-6"><div className="flex items-center justify-between"><p className="font-bold text-ink">{editing ? "Edit tag" : "Add tag"}</p><button type="button" onClick={() => start()} aria-label="Close form" className="text-slate hover:text-ink"><X size={18} /></button></div><form onSubmit={save} className="mt-5 grid gap-4 sm:grid-cols-2"><Input label="Name" value={name} onChange={(event) => setName(event.target.value)} required /><Input label="Slug (optional)" value={slug} onChange={(event) => setSlug(event.target.value)} /><div className="sm:col-span-2"><Button loading={saving}>{editing ? "Save changes" : "Create tag"}</Button></div></form></Card> : null}{loading ? <LoadingState label="Loading tags" /> : <Card className="mt-7 divide-y divide-line overflow-hidden">{items.length === 0 ? <div className="px-6 py-12 text-center text-sm text-slate">No tags match this search.</div> : items.map((tag) => <div key={tag.id} className="flex items-center justify-between gap-3 px-6 py-5"><div><p className="font-semibold text-ink">#{tag.name}</p><p className="mt-1 font-mono text-xs text-slate">/{tag.slug}</p></div><div className="flex gap-1"><button type="button" onClick={() => start(tag)} aria-label={`Edit ${tag.name}`} className="grid h-9 w-9 place-items-center rounded-lg text-slate hover:bg-mist hover:text-ink"><Pencil size={15} /></button><button type="button" onClick={() => remove(tag)} aria-label={`Delete ${tag.name}`} className="grid h-9 w-9 place-items-center rounded-lg text-slate hover:bg-red-50 hover:text-red-700"><Trash2 size={15} /></button></div></div>)}</Card>}</AdminShell>; }
export default function TagsPage() { return <AdminRoute><PermissionRoute permission="TAG_MANAGE"><TagsContent /></PermissionRoute></AdminRoute>; }
